version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: ELKOOD.ToDo.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=ELKOOD_ToDo;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=true;"
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: "YourSuperSecretKeyHereThatIsAtLeast32CharactersLong!"
      Jwt__Issuer: "ELKOOD-ToDo-API"
      Jwt__Audience: "ELKOOD-ToDo-Users"
      Jwt__ExpireMinutes: "60"
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge